apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cd.krantz.cloud
spec:
  secretName: cd-krantz-cloud-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: cd.krantz.cloud
  dnsNames:
    - cd.krantz.cloud
