apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: cd.krantz.cloud
spec:
  virtualhost:
    fqdn: cd.krantz.cloud
    tls:
      secretName: cd-krantz-cloud-tls
  routes:
    - services:
        - name: argocd-server
          port: 80
      conditions:
        - prefix: /
    - services:
        - name: argocd-server
          port: 443
          protocol: h2c
      conditions:
        - header:
            name: Content-Type
            contains: application/grpc
