apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectcontour

resources:
  - https://raw.githubusercontent.com/projectcontour/contour/v1.24.1/examples/render/contour.yaml

patchesStrategicMerge:
  - overlay/envoy-service.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: contour
      namespace: projectcontour
    path: patches/contour-deployment.yaml
