apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: governor

images:
  - name: governor
    newName: keikoproj/governor
    newTag: v0.3.4

resources:
  - https://raw.githubusercontent.com/keikoproj/governor/master/examples/pod-reaper.yaml

patchesJson6902:
  - target:
      group: batch
      version: v1beta1
      kind: CronJob
      name: pod-reaper
    path: patches/pod-reaper-job.yaml
