apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: projectcontour
    server: https://kubernetes.default.svc
  project: default
  source:
    path: contour
    repoURL: https://github.com/akrantz01/terraform-k8s-gitops.git
    targetRevision: HEAD
