apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - https://github.com/kubernetes-sigs/external-dns/kustomize

patchesStrategicMerge:
  - overlay/deployment.yaml

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: external-dns
    path: patches/clusterrole.yaml
